language: csharp
solution: ./TcpPing.sln
mono:
  - latest

install:
  - nuget restore ./src/TcpPing.sln
  - nuget install Machine.Specifications.Runner.Console

script:
  - xbuild /p:Configuration=Release ./TcpPing.sln
  - mono ./Machine.Specifications.Runner.Console*/tools/mspec.exe ./TcpPingTest/bin/Release/TcpPingTest.dll